export enum ROUTE {
  HOME = "/",
  NEW = "new",
  NEW_OTHER_WAY = "/new",
  FAVORITES = "favorites",
  SETTINGS = "settings",
  MOVIE = "/movie/",
  DETAILS = "movie/:imdbID",
  SIGN_IN = "sign-in",
  SIGN_IN_OTHER_WAY = "/sign-in",
  SIGN_UP = "sign-up",
  SIGN_UP_OTHER_WAY = "/sign-up",
  LOG_OUT = "log-out",
  RESSET_PASSWORD = "/reset-password",
  SEARCH = "search",
  NOT_FOUND = "*",
}
