export enum Color {
  Primary = "var(--primary)",
  PrimaryLight = "var(--primary-light)",
  Secondary = "var(--secondary)",
  ThemeBlack = "var(--theme-black)",
  ThemeWhite = "var(--theme-white)",
  Black = "var(--black)",
  White = "var(--white)",
  Dark = "var(--dark)",
  Graphite = "var(--graphite)",
  Error = "var(--error)",
  Light = "var(--light)",
  Green = "var(--green)",
  Yellow = "var(--yellow)",
  Orange = "var(--orange)",
}
